services:
  app:
    image: server-token-api
    build: .
    container_name: tokenapi
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./configs/configuration.env
  db:
    image: postgres:17
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./configs/configuration.env

volumes:
  postgres_data:
