
services:
  app:
    image: server-token-api
    build: .
    container_name: tokenapi
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_OPTIONS=${DB_OPTIONS}
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - ENV=${ENV}
      - ADDRESS=${ADDRESS}
      - TIMEOUT=${TIMEOUT}  
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
